version: '3.8'

services:
  dbpostgres:
    image: postgres:14.8-alpine3.18
    container_name: dbpostgres
    restart: always
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
